apiVersion: apps/v1                 # API Version of this Object
kind: Deployment                    # This Object Type
metadata:                           # Allows you to specify custom metadata
    name: $APP                       # Specifies the name of this object
spec:                               # The official specification matching object type schema
    sedlector:                         # Label selector for pods
        matchLabels:                    # Must match these label(s)
            dapp: $APP                    # Custom label with value
    template:                         # Template describes the pods that are created
        metadata:                       # Standard objects metadata
            labels:                       # Labels used to group/categorize objects
                app: $APP                  # The name of this template
        spec:                           # Specification of the desired behaviour of this pod
            containers:                   # List of containers belonging to this pod (cannot be changed/updated)
                - name: $APP                 # Name of this container
                  image: $IMAGE                # Docker image used for this container
                  ports:                      # Port mapping(s)
                      - containerPort: 80       # Number of port to expose on this pods ip address
                  readinessProbe:             # Periodic probe of container readiness. Container will be removed from endpoints if not ready
                      tcpSocket:                # tcpSocket is the action "type" of the probe
                          port: 80                # Number of port to open a connection to
                      initialDelaySeconds: 10   # Number of seconds to wait before probing
                      periodSeconds: 10         # How often to perform probe check
                  livenessProbe:              # Periodic probe of container readiness. Container will be removed from endpoints if not "alive"
                      tcpSocket:                # tcpSocket is the action "type" of the probe
                          port: 80                # Number of port to open a connection to
                      initialDelaySeconds: 15   # Number of seconds to wait before probing
                      perioddSeconds: 15         # How often to perform probe check
